######################################################################
#
# File name : top.udo
# Created on: Fri May 03 13:07:17 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

force -freeze sim:/top/clk 0 0, 1 {12.5 ns} -r 25ns
