######################################################################
#
# File name : top_wave.do
# Created on: Fri May 03 13:07:17 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
#if { [catch {[add wave *]}] } {}

### General Simulation ###
add wave -position insertpoint sim:/top/clk
add wave -position insertpoint sim:/top/counter
add wave -position insertpoint sim:/top/links_in(1)
add wave -position insertpoint sim:/top/header(1)
add wave -position insertpoint sim:/top/DTCIn_stubs(1)
add wave -position insertpoint sim:/top/pre_stubs(1)
add wave -position insertpoint sim:/top/stubs(1)
add wave -divider


### Stub Formatter Debugging ###
#add wave -position insertpoint sim:/top/clk
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/strip_number
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/pos_lut_out
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/stub_out.alpha
#add wave -position insertpoint sim:/top/DTCIn_stubs(0).bend
#add wave -position insertpoint sim:/top/pre_stubs(0).bend
#add wave -divider

### Link Formatter ###
#add wave -position insertpoint sim:/top/clk
#add wave -position insertpoint sim:/top/gLinksFormat(0)/LinkFormatterInstance/counter
#add wave -position insertpoint sim:/top/links_in(0)
#add wave -position insertpoint sim:/top/header(0)
#add wave -position insertpoint sim:/top/DTCIn_stubs(0)
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/tmp_buff
#add wave -position insertpoint sim:/top/pre_stubs(0)
#add wave -divider

### CoordinateCorrector ###
add wave -radix decimal -position insertpoint sim:/top/gStubFormatter(1)/CoordinateCorrectorInstance/stub_in.intrinsic
add wave -radix decimal -position insertpoint sim:/top/gStubFormatter(1)/CoordinateCorrectorInstance/matrix
add wave -radix decimal -position insertpoint sim:/top/gStubFormatter(1)/CoordinateCorrectorInstance/multiplied_matrix
add wave -position insertpoint sim:/top/gStubFormatter(1)/CoordinateCorrectorInstance/stub_out
add wave -divider
