######################################################################
#
# File name : top_wave.do
# Created on: Fri May 03 13:07:17 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
#if { [catch {[add wave *]}] } {}

### Stub Formatter Debugging ###
#add wave -position insertpoint sim:/top/clk
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/strip_number
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/pos_lut_out
#add wave -position insertpoint sim:/top/gStubFormatter(0)/StubFormatterInstance/stub_out.alpha
#add wave -position insertpoint sim:/top/DTCIn_stubs(0).bend
#add wave -position insertpoint sim:/top/stubs(0).bend


### Link Formatter ###
add wave -position insertpoint sim:/top/clk
add wave -position insertpoint sim:/top/gLinksFormat(0)/LinkFormatterInstance/counter
add wave -position insertpoint sim:/top/links_in(0)
add wave -position insertpoint sim:/top/header(0)
add wave -position insertpoint sim:/top/DTCIn_stubs(0)
