######################################################################
#
# File name : top_simulate.do
# Created on: Fri May 31 12:05:16 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.top

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_wave.do}

view wave
view structure
view signals

do {top.udo}

run 1000ns
