######################################################################
#
# File name : top_wave.do
# Created on: Fri May 03 13:07:17 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
