######################################################################
#
# File name : top_compile.do
# Created on: Fri May 03 15:22:47 BST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -2008 -work xil_defaultlib  \
"../../../../DTC-front.srcs/sources_1/new/LinkGenerator.vhd" \
"../../../../DTC-front.srcs/sources_1/new/top.vhd" \


