######################################################################
#
# File name : tb_compile.do
# Created on: Fri Mar 09 11:37:26 GMT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../top.srcs/sources_1/ip/blockram_512x36/sim/blockram_512x36.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/common/utilities.vhd" \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/Sorter/BinarySortTree.vhd" \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/Sorter/BinarySortTree2.vhd" \
"../../../../../cactusupgrades/components/mp7_datapath/firmware/hdl/mp7_data_types.vhd" \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/common/xml_utilities.vhd" \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/packages/others.vhd" \
"../../../../../cactusupgrades/projects/tracktrigger/dtc/firmware/hdl/testbench/TestBench.vhd" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

