######################################################################
#
# File name : tb_wave.do
# Created on: Fri Mar 09 11:37:27 GMT 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
